<aside class="main-sidebar">
   <div class="sidebar">
      <ul class="sidebar-menu">
         <li class="active">
            <a href="index.php"><i class="fa fa-tachometer"></i><span>Dashboard</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li class="active">
            <a href="account.php"><i class="fa fa-shopping-bag"></i><span>Accounts</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li class="active">
            <a href="contacts.php"><i class="hvr-buzz-out fa fa-address-book-o"></i><span>Contacts</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li class="active">
            <a href="leads.php"><i class="fa fa-users"></i><span>Leads</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li class="active">
            <a href="oppurtunity.php"><i class="fa fa-dollar"></i><span>Oppurtunity</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="event.php">
            <i class="fa fa-calendar"></i> <span>Event</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="users.php">
            <i class="fa fa-users"></i><span>Users</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="teams.php">
            <i class="fa fa-braille"></i><span>Team</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="quotations.php">
            <i class="fa fa-file-text"></i><span>Quotations</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-shopping-cart"></i><span>Sales</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="orders.php">Orders</a></li>
               <li><a href="products.php">Product Management</a></li>
               <li><a href="#">Proposals</a></li>
               <li><a href="#">Estimates</a></li>
               <li><a href="#">Items</a></li>
               <li><a href="#">Payments</a></li>
               <li><a href="#">Tax Rates</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-shopping-basket"></i><span>Transaction</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="#">New Deposit</a></li>
               <li><a href="#">New Expense</a></li>
               <li><a href="#">Transfer</a></li>
               <li><a href="#">View transaction</a></li>
               <li><a href="#">Balance Sheet</a></li>
               <li><a href="#">Transfer Report</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-book"></i><span>Task</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="#">Running Task</a></li>
               <li><a href="#">Archive Task</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-shopping-bag"></i><span>Accounting</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="#">Suppliers Management</a></li>
               <li><a href="#">Customer Management</a></li>
               <li><a href="#">Purchase Management</a></li>
               <li><a href="#">Sales management</a></li>
               <li><a href="#">Expenses</a></li>
               <li><a href="#">Purchase Outstandings</a></li>
               <li><a href="#">Sales Outstandings</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-file-text"></i><span>Report</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="#">Project Report</a></li>
               <li><a href="#">Client Report</a></li>
               <li><a href="#">Expense Report</a></li>
               <li><a href="#">Income expense comparesion</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-bitbucket-square"></i><span>Stock</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="#">Stock category</a></li>
               <li><a href="#">Manage Stock</a></li>
               <li><a href="#">Assign stock</a></li>
            </ul>
         </li>
         <li>
            <a href="#">
            <i class="fa fa-home"></i> <span>Companies</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="#">
            <i class="fa fa-user-circle"></i><span>User</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="#">
            <i class="fa fa-file-text"></i> <span>Documents</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="#">
            <i class="fa fa-file-text"></i> <span>Notice Board</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="#">
            <i class="fa fa-envelope-o"></i> <span>Message</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="#">
            <i class="fa fa-comment"></i> <span>Notes</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
      </ul>
   </div>
</aside>