<aside class="main-sidebar">
   <div class="sidebar">
      <ul class="sidebar-menu">
         <li class="active">
            <a href="index.php"><i class="fa fa-tachometer"></i><span>Dashboard</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li class="active">
            <a href="account.php"><i class="fa fa-shopping-bag"></i><span>Accounts</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li class="active">
            <a href="contacts.php"><i class="hvr-buzz-out fa fa-address-book-o"></i><span>Contacts</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li class="active">
            <a href="leads.php"><i class="fa fa-users"></i><span>Leads</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li class="active">
            <a href="oppurtunity.php"><i class="fa fa-dollar"></i><span>Oppurtunity</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="event.php">
            <i class="fa fa-calendar"></i> <span>Event</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="users.php">
            <i class="fa fa-users"></i><span>Users</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="teams.php">
            <i class="fa fa-braille"></i><span>Team</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="quotations.php">
            <i class="fa fa-file-text"></i><span>Quotations</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
         <li>
            <a href="quoteconfig.php">
            <i class="fa fa-file-text"></i><span>Quote Config</span>
            <span class="pull-right-container">
            </span>
            </a>
         </li>
          <li class="treeview">
            <a href="#">
            <i class="ti-layout-accordion-list"></i><span>Suppliers</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="supplier.php">Add Supplier</a></li>
               <li><a href="managesupplier.php">Manage Supplier</a></li>
               <li><a href="#">Supplier Ledger</a></li>
               <li><a href="#">Supplier Payments</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="ti-bag"></i><span>Products</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="category.php">Category</a></li>
               <li><a href="products.php">Add Product</a></li>
               <li><a href="manageproducts.php">Manage Product</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="ti-layout-accordion-list"></i><span>Sell</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="neworder.php">New Sell</a></li>
               <li><a href="order.php">Manage  Sell</a></li>
               <li><a href="#">POS Sell</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="ti-shopping-cart"></i><span>Purchase</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="newpurchase.php">Add Purchase</a></li>
               <li><a href="managepurchase.php">Manage Purchase</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="ti-bar-chart"></i><span>Stock</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="stock.php">Stock Report</a></li>
               <li><a href="outofstock.php">Out of Stock</a></li>
               <li><a href="#">Stock Report (Supplier Wise)</a></li>
               <li><a href="#">Stock Report (Product Wise)</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="ti-book"></i><span>Report</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="#">Purchase Report</a></li>
               <li><a href="#">Sales Report (Product Wise)</a></li>
               <li><a href="#">Profit Report (Invoice Wise)</a></li>
               <li><a href="#">Todays Report</a></li>
               <li><a href="#">Sales Report</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="ti-briefcase"></i><span>Bank</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="newbank.php">Add New Bank</a></li>
               <li><a href="banktransaction.php">Bank Transaction</a></li>
               <li><a href="managebank.php">Manage Bank</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-credit-card"></i><span>Expense</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="expense.php">Add Expense</a></li>
               <li><a href="expensestatement.php">Expense Statement</a></li>
            </ul>
         </li>
         <!--li class="treeview">
            <a href="#">
            <i class="fa fa-shopping-cart"></i><span>Sales</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="order.php">Orders</a></li>
               <li><a href="products.php">Product Management</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-shopping-basket"></i><span>Transaction</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="#">New Deposit</a></li>
               <li><a href="#">Expenses</a></li>
               <li><a href="#">Purchase Outstandings</a></li>
               <li><a href="#">Sales Outstandings</a></li>
               <li><a href="#">View transaction</a></li>
               <li><a href="#">Balance Sheet</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-shopping-bag"></i><span>Accounting</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="suppliers.php">Suppliers Management</a></li>
               <li><a href="#">Purchase Management</a></li>
               <li><a href="#">Sales management</a></li>
            </ul>
         </li>
         <li class="treeview">
            <a href="#">
            <i class="fa fa-bitbucket-square"></i><span>Stock</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
               <li><a href="#">Stock category</a></li>
               <li><a href="#">Manage Stock</a></li>
               <li><a href="#">Assign stock</a></li>
            </ul>
         </li-->
      </ul>
   </div>
</aside>